production:
  redis:
    url: redis://YOUR_REDIS_URL
  pusher:
    app_id: YOUR_PUSHER_APP_ID
    key:    YOUR_PUSHER_KEY
    secret: YOUR_PUSHER_SECRET
  rails:
    # You get a Travis token on the Travis profile page by signing in to your application via Github OAuth2.
    url: "YOUR_GITHUB_USERNAME:YOUR_TRAVIS_TOKEN@travis-ci.org"
  oauth2:
    client_id: YOUR_GITHUB_CLIENT_ID
    client_secret: YOUR_GITHUB_CLIENT_SECRET

development:
  redis:
    url: redis://localhost:6379
  pusher:
    app_id: YOUR_PUSHER_APP_ID
    key:    YOUR_PUSHER_KEY
    secret: YOUR_PUSHER_SECRET
  rails:
    host: localhost:3000
  oauth2:
    client_id: YOUR_GITHUB_CLIENT_ID
    client_secret: YOUR_GITHUB_CLIENT_SECRET

test:
  redis:
    url: redis://localhost:6379
